feat: Add unhighlightedTag prop
bvaughn/react-highlight-words pull request #99
Opened 2022-03-08 11:21 UTC by kaungmyatlwin

## Description

This PR adds ability to render custom HTML tags / React Nodes instead of defaulting to `<span>` element.

## Problem
Defaulting to `<span>` is a good idea and must have, but sometimes we have edge cases where you need to pass custom React nodes in order to provide additional functionalities. Please see the Use Case below.

## Use Case
Should be able to render `<a>` tags whenever necessary or pass React components (such as `<Linkify`: https://github.com/tasti/react-linkify) to render the links properly.

2022-04-05 21:21 UTC, sergei-startsev requested changes
@kaungmyatlwin Thanks for your contribution. I like the idea to have consistent `highlight*` and `unhighlight*` properties. Left a comment.

2022-04-05 21:21 UTC, sergei-startsev commented on src/Highlighter.test.js
> +  it('should use :unhighlightTag if provided', () => {
Could you also add tests to prove that `highlightTag` can be a functional/class component?

2022-04-06 12:38 UTC, kaungmyatlwin commented
Hi @sergei-startsev , thanks for replying. I've added two test cases f8d34a1b4be84b12804933bd01537c20f7e8154f for `unhighlightTag` to test if they can be functional/class component.

Please have a look.

2022-04-13 22:07 UTC, sergei-startsev commented
@kaungmyatlwin please exclude `package-lock.json`, `yarn.lock` from the PR.

2022-04-13 22:07 UTC, sergei-startsev requested changes
@kaungmyatlwin please exclude package-lock.json, yarn.lock from the PR.

2022-04-15 10:30 UTC, kaungmyatlwin commented
@sergei-startsev Rebased against master. Can you check?

2022-04-18 19:56 UTC, sergei-startsev approved these changes

2022-04-18 19:56 UTC, merged

2022-04-18 19:57 UTC, sergei-startsev commented
@kaungmyatlwin your changes will be included into the next release.

2023-01-19 16:42 UTC, JeffreyATW commented
@sergei-startsev Hi there! Would you mind creating a new release with this change? Thanks!

2023-01-22 22:16 UTC, sergei-startsev commented
@JeffreyATW check out https://www.npmjs.com/package/react-highlight-words/v/0.20.0